# Cloudflare Tunnel 配置文件
tunnel: a3-tt-live-ai

ingress:
  # 规则 1: 将 ai.maraecowell.com 指向本地 Flask 服务
  - hostname: ai.maraecowell.com
    service: http://127.0.0.1:8000
    originRequest:
      httpHostHeader: ai.maraecowell.com
      noTLSVerify: true
  
  # 规则 2: catch-all 规则 - 处理其他所有请求，返回 404
  # 重要：此规则必须放在最后
  - service: http_status:404
